// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whubdhmrhtxgtcksuynn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndodWJkaG1yaHR4Z3Rja3N1eW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzI4NjMsImV4cCI6MjA3MjYwODg2M30.EAHUbgefavmNvYy0z8892G5fk-0kpEq7lt4lgkIVHoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});